### ISSUE TITLE
Unexpected extension byte 

### ISSUE THREAD

**Issue by Moh-Snoussi** [zonble/simple_rc4_dart#1]
## Issue
I am getting a FormatException: Unexpected extension byte ...

this is caused by the utf8.decode when the given list is not well formed.

## Solution
The problem can be solved by adding the second parameter  {[bool](https://api.dart.dev/be/181224/dart-core/bool-class.html)? allowMalformed} to the utf8.decode(list, allowMalformed=true)

### Improvement suggestion:

https://github.com/zonble/simple_rc4_dart/blob/a739a2da8c724cc5d3c013172c53790cc8a65c31/lib/src/simple_rc4_base.dart#L65

To allow the {[bool](https://api.dart.dev/be/181224/dart-core/bool-class.html)? allowMalformed} so that it can be passed with a default parameter like:
```dart
  String decodeBytes(List<int> bytes, {bool allowMalformed=true}) => utf8.decode(_crypt(bytes), allowMalformed=allowMalformed);
```
the same improvment can be also added to the decodeString function on: 
https://github.com/zonble/simple_rc4_dart/blob/a739a2da8c724cc5d3c013172c53790cc8a65c31/lib/src/simple_rc4_base.dart#L92
https://github.com/zonble/simple_rc4_dart/blob/a739a2da8c724cc5d3c013172c53790cc8a65c31/lib/src/simple_rc4_base.dart#L96

**Comment by zonble** [comment]
I've merged your PR. Thanks!
